<?php
return [
    [
        'first_name' => 'Matt',
        'last_name'  => 'Mapleton',
        'company'    => '',
        'address_1'  => '124 Brien Ave',
        'address_2'  => '',
        'city'       => 'Sault Ste. Marie',
        'state'      => 'ON',
        'postcode'   => 'P6B 2Y6',
        'country'    => 'CA',
        'email'      => 'thomas.mapleton@example.com',
        'phone'      => '416-555-1234',
    ],
    [
        'first_name' => 'Sir Matt',
        'last_name'  => 'Oakwood',
        'company'    => '',
        'address_1'  => '731 Mortimer Ave',
        'address_2'  => '',
        'city'       => 'Thunder Bay',
        'state'      => 'ON',
        'postcode'   => 'P7E 1Y7',
        'country'    => 'CA',
        'email'      => 'sir.thomas.oakwood@example.com',
        'phone'      => '604-555-5678',
    ],
    [
        'first_name' => 'Matt the Third',
        'last_name'  => 'Pines',
        'company'    => '',
        'address_1'  => '234 Archibald St N',
        'address_2'  => '',
        'city'       => 'Thunder Bay',
        'state'      => 'ON',
        'postcode'   => 'P7C 3Y2',
        'country'    => 'CA',
        'email'      => 'thomas.third@example.com',
        'phone'      => '514-555-7890',
    ],
    [
        'first_name' => 'Lord Matt',
        'last_name'  => 'Redwood',
        'company'    => '',
        'address_1'  => '394 Cairnsmore St',
        'address_2'  => '',
        'city'       => 'Winnipeg',
        'state'      => 'MB',
        'postcode'   => 'R2X 1Y6',
        'country'    => 'CA',
        'email'      => 'lord.thomas.redwood@example.com',
        'phone'      => '403-555-1122',
    ],
    [
        'first_name' => 'Matt Jr.',
        'last_name'  => 'Birchwood',
        'company'    => '',
        'address_1'  => '70 Millcrest Way SW',
        'address_2'  => '',
        'city'       => 'Calgary',
        'state'      => 'AB',
        'postcode'   => 'T2Y 2J3',
        'country'    => 'CA',
        'email'      => 'thomas.jr@example.com',
        'phone'      => '780-555-3344',
    ],
    [
        'first_name' => 'Matt IV',
        'last_name'  => 'Cedar',
        'company'    => '',
        'address_1'  => '11225 82 Ave',
        'address_2'  => '',
        'city'       => 'Delta',
        'state'      => 'BC',
        'postcode'   => 'V4C 2B8',
        'country'    => 'CA',
        'email'      => 'thomas.iv@example.com',
        'phone'      => '902-555-5567',
    ],
    [
        'first_name' => 'Sir Thomas the Brave',
        'last_name'  => 'Spruce',
        'company'    => '',
        'address_1'  => '4880 Boundary Rd',
        'address_2'  => '',
        'city'       => 'Burnaby',
        'state'      => 'BC',
        'postcode'   => 'V5R 2N9',
        'country'    => 'CA',
        'email'      => 'sir.thomas.brave@example.com',
        'phone'      => '613-555-7788',
    ],
    [
        'first_name' => 'Thomas the Fearless',
        'last_name'  => 'Elm',
        'company'    => '',
        'address_1'  => '3558 W 32nd Ave',
        'address_2'  => '',
        'city'       => 'Vancouver',
        'state'      => 'BC',
        'postcode'   => 'V6S 1Z2',
        'country'    => 'CA',
        'email'      => 'thomas.fearless@example.com',
        'phone'      => '204-555-8899',
    ],
    [
        'first_name' => 'Thomas the Great',
        'last_name'  => 'Aspen',
        'company'    => '',
        'address_1'  => '3720 W 8th Ave',
        'address_2'  => '',
        'city'       => 'Vancouver',
        'state'      => 'BC',
        'postcode'   => 'V6R 1Z3',
        'country'    => 'CA',
        'email'      => 'thomas.great@example.com',
        'phone'      => '418-555-4455',
    ],
    [
        'first_name' => 'Thomas of Maple',
        'last_name'  => 'Hollow',
        'company'    => '',
        'address_1'  => '6124 Eagle Dr',
        'address_2'  => '',
        'city'       => 'Whistler',
        'state'      => 'BC',
        'postcode'   => 'V0N 1B6',
        'country'    => 'CA',
        'email'      => 'thomas.maple@example.com',
        'phone'      => '306-555-9900',
    ],
];
