<?php
return [
    [
        'first_name' => 'Matt',
        'last_name'  => 'Jefferson',
        'company'    => '',
        'address_1'  => '11807 40th Ave S',
        'address_2'  => '',
        'city'       => 'Tukwila',
        'state'      => 'WA',
        'postcode'   => '98168',
        'country'    => 'US',
        'email'      => 'thomas.jefferson@example.com',
        'phone'      => '202-555-1234',
    ],
    [
        'first_name' => 'Sir Matthew',
        'last_name'  => 'Madison',
        'company'    => '',
        'address_1'  => '3310 S Ainsworth Ave',
        'address_2'  => '',
        'city'       => 'Tacoma',
        'state'      => 'WA',
        'postcode'   => '98418',
        'country'    => 'US',
        'email'      => 'sir.thomas.madison@example.com',
        'phone'      => '217-555-5678',
    ],
    [
        'first_name' => 'Matt the Third',
        'last_name'  => 'Lincoln',
        'company'    => '',
        'address_1'  => '3416 SE 15th Ave',
        'address_2'  => '',
        'city'       => 'Portland',
        'state'      => 'OR',
        'postcode'   => '97202',
        'country'    => 'US',
        'email'      => 'thomas.third.lincoln@example.com',
        'phone'      => '417-555-7890',
    ],
]
